const Footer = () => {
  return (
    <div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
      <div>Foter</div>
    </div>
  );
};

export default Footer;
